/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/modeles3D/IPHONE13.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAM_EYE.geometry}
        material={materials['cam eye']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAM_BASE.geometry}
        material={materials['cam base']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAMERA_RING.geometry}
        material={materials.side}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAM_EYE001.geometry}
        material={materials['cam eye']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAMERA_RING001.geometry}
        material={materials.side}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAM_EYE002.geometry}
        material={materials['cam eye']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAMERA_RING002.geometry}
        material={materials.side}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAMGLASS.geometry}
        material={materials['cam ']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAM_GLASS001.geometry}
        material={materials['cam ']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.CAM_GLASS.geometry}
        material={materials['cam ']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SENSOR.geometry}
        material={materials['cam ']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FLASH_LIGHT.geometry}
        material={materials.flash}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.F_CAM.geometry}
        material={materials['cam base']}
        position={[0, 0, -0.006]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Apple_logo.geometry}
        material={materials['Material.030']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SENSOR001.geometry}
        material={materials['cam eye']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.MAIN_BODY.geometry}
        material={materials.side}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.SCREEN.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.FRONT_RING.geometry}
        material={materials['f ring']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.BACK_COVER.geometry}
        material={materials.back}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.b1.geometry}
        material={materials['cam base']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.b2.geometry}
        material={materials['cam base']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.b3.geometry}
        material={materials['cam base']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.b4.geometry}
        material={materials['cam base']}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.b5.geometry}
        material={materials['cam base']}
      />
    </group>
  )
}

export default Model;

useGLTF.preload('/modeles3D/IPHONE13.glb')
