/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/modeles3D/S11.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={20} position-y={2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials.Plastic_Glossy_Side}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_1.geometry}
          material={materials.Plastic_Mate_Side}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_2.geometry}
          material={materials.Screen}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_3.geometry}
          material={materials.Glass}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_4.geometry}
          material={materials.Black_Chrome}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001_5.geometry}
          material={materials.Redmi_Logo}
        />
        <group position={[0, 0.078, 0.004]} rotation={[0.024, 0, 0]} scale={[1, 0.9, 0.9]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={materials.Plastic_Mate_Side}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube008_1.geometry}
            material={materials.Plastic_Mate_Side}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AudioContacts.geometry}
          material={materials.Brass}
          position={[-0.025, 0.078, 0]}
          scale={[1.003, 1.001, 0.987]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Camera_Outer_Frame.geometry}
          material={materials.Plastic_Mate_Side}
          position={[0.019, 0.054, 0]}
          scale={[1.003, 1.001, 0.987]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Camera_Inner_Frame.geometry}
            material={materials.Black_Chrome}
            position={[0, 0.013, -0.007]}
            scale={[0.991, 1.014, 1]}>
            <group
              position={[0, 0, 0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.009, 1, 0.987]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001.geometry}
                material={materials.Anisotropic_In_Camera}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001_1.geometry}
                material={materials.Plastic_Glossy_Side}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane001_2.geometry}
                material={materials.Plastic_Mate_Side}
              />
            </group>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Main_Camera_Glass.geometry}
              material={materials.Glass}
              scale={[1.009, 0.987, 1]}
            />
            <group
              position={[0, 0, 0.001]}
              rotation={[-Math.PI / 2, 0, 0]}
              scale={[1.009, 1, 0.987]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002.geometry}
                material={materials.Glass}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Plane002_1.geometry}
                material={materials.Black_Chrome}
              />
            </group>
          </mesh>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Extra_Cameras_Glass.geometry}
            material={materials.Glass}
            position={[0, -0.013, -0.005]}
          />
          <group position={[-0.005, -0.011, -0.005]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube010.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube010_1.geometry}
              material={materials.LED}
            />
          </group>
          <group position={[0.004, -0.011, -0.002]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle002.geometry}
              material={materials.Plastic_Mate_Side}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle002_1.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle002_2.geometry}
              material={materials.Black_Chrome}
            />
          </group>
          <group position={[-0.005, -0.002, -0.002]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle001.geometry}
              material={materials.Plastic_Mate_Side}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle001_1.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle001_2.geometry}
              material={materials.Black_Chrome}
            />
          </group>
          <group position={[0.004, -0.002, -0.003]} rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle.geometry}
              material={materials.Plastic_Mate_Side}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle_1.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circle_2.geometry}
              material={materials.Black_Chrome}
            />
          </group>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006.geometry}
            material={materials.ExtraCamerasModule}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={materials.Plastic_Mate_Side}
          />
        </mesh>
        <group
          position={[0, 0.073, 0.003]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.702, 0.691, 0.701]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere.geometry}
            material={materials.Glass}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_1.geometry}
            material={materials.Black_Chrome}
          />
        </group>
        <group scale={[1.003, 1.001, 0.987]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={materials.Material}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube007_1.geometry}
            material={materials.Material}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.SIM.geometry}
          material={materials.Plastic_Mate_Side}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Toch_Sensor.geometry}
          material={materials.Plastic_Mate_Side}
        />
        <group position={[0, -0.077, 0]} scale={[1.003, 1.001, 0.987]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012.geometry}
            material={materials.Plastic_Mate_Side}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_1.geometry}
            material={materials.Gold_Contacts_USB_C}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube012_2.geometry}
            material={materials.Aluminum_USB_C}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Volume_Buttons.geometry}
          material={materials.Plastic_Mate_Side}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/modeles3D/S11.glb')
